function [plant_model, validation_error] = identify_the_plant( ...
                                               estimation_iddata, ...
                                               validation_iddata)
    % Estimate the plant model using a transfer function
    plant_model = tfest(estimation_iddata, 5, 4);
    
    % Validate the estimated model with the validation data
    [y_est, ~] = lsim(plant_model, ...
                      validation_iddata.InputData, ...
                      validation_iddata.SamplingInstants);
    validation_error = norm(validation_iddata.OutputData - y_est);
end