function result = recording_output(yout)
    result_timetable = timetable(yout{2}.Values.Data,squeeze(yout{3}.Values.Data), ...
                                 'RowTimes',seconds(yout{2}.Values.Time));
    result_timetable.Properties.VariableNames = ["Input", "Output"];
    result = timetable2iddata(result_timetable, ...
                              "INPUTNAME", "Input", ...
                              "OUTPUTNAME", "Output");
end